//User Types
export const USER_DETAILS_SUCCESS='USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAILURE='USER_DETAILS_FAILURE'
//Education Types
export const EDUCATION_DETAILS_SUCCESS='EDUCATION_DETAILS_SUCCESS'
export const EDUCATION_DETAILS_FAILURE='EDUCATION_DETAILS_FAILURE'

//Project Types
export const PROJECTS_DETAILS_SUCCESS='PROJECTS_DETAILS_SUCCESS'
export const PROJECTS_DETAILS_FAILURE='PROJECTS_DETAILS_FAILURE'

//Skills Types
export const SKILLS_DETAILS_SUCCESS='SKILLS_DETAILS_SUCCESS'
export const SKILLS_DETAILS_FAILURE='SKILLS_DETAILS_FAILURE'

//Services Types
export const SERVICES_DETAILS_SUCCESS='SERVICES_DETAILS_SUCCESS'
export const SERVICES_DETAILS_FAILURE='SERVICES_DETAILS_FAILURE'